config/routes.rb
Rails.application.routes.draw do
  resources :stores
  resources :contacts
  resources :resources
  resources :gives
  resources :abouts
  resources :voices
  get 'welcome/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/store.rb
class Store < ApplicationRecord
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:name)
    end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_with(model: store, local: true) do |form| %>
  <% if store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
        <% store.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
<h1>Awesome Image Hover in Pure CSS Part I</h1>
<div class="content">
  <h2>Lily</h2>
  <div class="grid">
      <figure class="effect-lily">
          <img src="https://tympanus.net/Development/HoverEffectIdeas/img/12.jpg" alt="img12"/>
          <figcaption>
              <div>
                  <h2>Nice <span>Lily</span></h2>
                  <p>Lily likes to play with crayons and pencils</p>
              </div>
              <a href="#">View more</a>
          </figcaption>           
      </figure>
      <figure class="effect-lily">
          <img src="https://tympanus.net/Development/HoverEffectIdeas/img/1.jpg" alt="img1"/>
          <figcaption>
              <div>
                  <h2>Nice <span>Lily</span></h2>
                  <p>Lily likes to play with crayons and pencils</p>
              </div>
              <a href="#">View more</a>
          </figcaption>           
      </figure>
  </div>
  <h2>Sadie</h2>
  <div class="grid">
      <figure class="effect-sadie">
          <img src="https://tympanus.net/Development/HoverEffectIdeas/img/2.jpg" alt="img02"/>
          <figcaption>
              <h2>Holy <span>Sadie</span></h2>
              <p>Sadie never took her eyes off me. <br>She had a dark soul.</p>
              <a href="#">View more</a>
          </figcaption>           
      </figure>
      <figure class="effect-sadie">
          <img src="https://tympanus.net/Development/HoverEffectIdeas/img/14.jpg" alt="img14"/>
          <figcaption>
              <h2>Holy <span>Sadie</span></h2>
              <p>Sadie never took her eyes off me. <br>She had a dark soul.</p>
              <a href="#">View more</a>
          </figcaption>           
      </figure>
  </div>
  <h2>Honey</h2>
  <div class="grid">
      <figure class="effect-honey">
          <img src="https://tympanus.net/Development/HoverEffectIdeas/img/4.jpg" alt="img04"/>
          <figcaption>
              <h2>Dreamy <span>Honey</span> <i>Now</i></h2>
              <a href="#">View more</a>
          </figcaption>           
      </figure>
      <figure class="effect-honey">
          <img src="https://tympanus.net/Development/HoverEffectIdeas/img/5.jpg" alt="img05"/>
          <figcaption>
              <h2>Dreamy <span>Honey</span> <i>Now</i></h2>
              <a href="#">View more</a>
          </figcaption>           
      </figure>
  </div>
  <h2>Layla</h2>
  <div class="grid">
      <figure class="effect-layla">
          <img src="https://tympanus.net/Development/HoverEffectIdeas/img/6.jpg" alt="img06"/>
          <figcaption>
              <h2>Crazy <span>Layla</span></h2>
              <p>When Layla appears, she brings an eternal summer along.</p>
              <a href="#">View more</a>
          </figcaption>           
      </figure>
      <figure class="effect-layla">
          <img src="https://tympanus.net/Development/HoverEffectIdeas/img/3.jpg" alt="img03"/>
          <figcaption>
              <h2>Crazy <span>Layla</span></h2>
              <p>When Layla appears, she brings an eternal summer along.</p>
              <a href="#">View more</a>
          </figcaption>           
      </figure>
  </div>
  <h2>Zoe</h2>
  <div class="grid">
      <figure class="effect-zoe">
          <img src="https://tympanus.net/Development/HoverEffectIdeas/img/25.jpg" alt="img25"/>
          <figcaption>
              <h2>Creative <span>Zoe</span></h2>
              <p class="icon-links">
                  <a href="#"><span class="icon-heart"></span></a>
                  <a href="#"><span class="icon-eye"></span></a>
                  <a href="#"><span class="icon-paper-clip"></span></a>
              </p>
              <p class="description">Zoe never had the patience of her sisters. She deliberately punched the bear in his face.</p>
          </figcaption>           
      </figure>
      <figure class="effect-zoe">
          <img src="https://tympanus.net/Development/HoverEffectIdeas/img/26.jpg" alt="img26"/>
          <figcaption>
              <h2>Creative <span>Zoe</span></h2>
              <p class="icon-links">
                  <a href="#"><span class="icon-heart"></span></a>
                  <a href="#"><span class="icon-eye"></span></a>
                  <a href="#"><span class="icon-paper-clip"></span></a>
              </p>
              <p class="description">Zoe never had the patience of her sisters. She deliberately punched the bear in his face.</p>
          </figcaption>           
      </figure>
  </div>
  <h2>Oscar</h2>
  <div class="grid">
      <figure class="effect-oscar">
          <img src="https://tympanus.net/Development/HoverEffectIdeas/img/9.jpg" alt="img09"/>
          <figcaption>
              <h2>Warm <span>Oscar</span></h2>
              <p>Oscar is a decent man. He used to clean porches with pleasure.</p>
              <a href="#">View more</a>
          </figcaption>           
      </figure>
      <figure class="effect-oscar">
          <img src="https://tympanus.net/Development/HoverEffectIdeas/img/10.jpg" alt="img10"/>
          <figcaption>
              <h2>Warm <span>Oscar</span></h2>
              <p>Oscar is a decent man. He used to clean porches with pleasure.</p>
              <a href="#">View more</a>
          </figcaption>           
      </figure>
  </div>
  <h2>Marley</h2>
  <div class="grid">
      <figure class="effect-marley">
          <img src="https://tympanus.net/Development/HoverEffectIdeas/img/11.jpg" alt="img11"/>
          <figcaption>
              <h2>Sweet <span>Marley</span></h2>
              <p>Marley tried to convince her but she was not interested.</p>
              <a href="#">View more</a>
          </figcaption>           
      </figure>
      <figure class="effect-marley">
          <img src="https://tympanus.net/Development/HoverEffectIdeas/img/12.jpg" alt="img12"/>
          <figcaption>
              <h2>Sweet <span>Marley</span></h2>
              <p>Marley tried to convince her but she was not interested.</p>
              <a href="#">View more</a>
          </figcaption>           
      </figure>
  </div>
  <h2>Ruby</h2>
  <div class="grid">
      <figure class="effect-ruby">
          <img src="https://tympanus.net/Development/HoverEffectIdeas/img/13.jpg" alt="img13"/>
          <figcaption>
              <h2>Glowing <span>Ruby</span></h2>
              <p>Ruby did not need any help. Everybody knew that.</p>
              <a href="#">View more</a>
          </figcaption>           
      </figure>
      <figure class="effect-ruby">
          <img src="https://tympanus.net/Development/HoverEffectIdeas/img/14.jpg" alt="img14"/>
          <figcaption>
              <h2>Glowing <span>Ruby</span></h2>
              <p>Ruby did not need any help. Everybody knew that.</p>
              <a href="#">View more</a>
          </figcaption>           
      </figure>
  </div>
  <h2>Roxy</h2>
  <div class="grid">
      <figure class="effect-roxy">
          <img src="https://tympanus.net/Development/HoverEffectIdeas/img/15.jpg" alt="img15"/>
          <figcaption>
              <h2>Charming <span>Roxy</span></h2>
              <p>Roxy was my best friend. She'd cross any border for me.</p>
              <a href="#">View more</a>
          </figcaption>           
      </figure>
      <figure class="effect-roxy">
          <img src="https://tympanus.net/Development/HoverEffectIdeas/img/1.jpg" alt="img01"/>
          <figcaption>
              <h2>Charming <span>Roxy</span></h2>
              <p>Roxy was my best friend. She'd cross any border for me.</p>
              <a href="#">View more</a>
          </figcaption>           
      </figure>
  </div>
  <h2>Bubba</h2>
  <div class="grid">
      <figure class="effect-bubba">
          <img src="https://tympanus.net/Development/HoverEffectIdeas/img/2.jpg" alt="img02"/>
          <figcaption>
              <h2>Fresh <span>Bubba</span></h2>
              <p>Bubba likes to appear out of thin air.</p>
              <a href="#">View more</a>
          </figcaption>           
      </figure>
      <figure class="effect-bubba">
          <img src="https://tympanus.net/Development/HoverEffectIdeas/img/16.jpg" alt="img16"/>
          <figcaption>
              <h2>Fresh <span>Bubba</span></h2>
              <p>Bubba likes to appear out of thin air.</p>
              <a href="#">View more</a>
          </figcaption>           
      </figure>
  </div>
  <h2>Romeo</h2>
  <div class="grid">
      <figure class="effect-romeo">
          <img src="https://tympanus.net/Development/HoverEffectIdeas/img/17.jpg" alt="img17"/>
          <figcaption>
              <h2>Wild <span>Romeo</span></h2>
              <p>Romeo never knows what he wants. He seemed to be very cross about something.</p>
              <a href="#">View more</a>
          </figcaption>           
      </figure>
      <figure class="effect-romeo">
          <img src="https://tympanus.net/Development/HoverEffectIdeas/img/18.jpg" alt="img18"/>
          <figcaption>
              <h2>Wild <span>Romeo</span></h2>
              <p>Romeo never knows what he wants. He seemed to be very cross about something.</p>
              <a href="#">View more</a>
          </figcaption>           
      </figure>
  </div>
  <h2>Dexter</h2>
  <div class="grid">
      <figure class="effect-dexter">
          <img src="https://tympanus.net/Development/HoverEffectIdeas/img/19.jpg" alt="img19"/>
          <figcaption>
              <h2>Strange <span>Dexter</span></h2>
              <p>Dexter had his own strange way. You could watch him training ants.</p>
              <a href="#">View more</a>
          </figcaption>           
      </figure>
      <figure class="effect-dexter">
          <img src="https://tympanus.net/Development/HoverEffectIdeas/img/12.jpg" alt="img12"/>
          <figcaption>
              <h2>Strange <span>Dexter</span></h2>
              <p>Dexter had his own strange way. You could watch him training ants.</p>
              <a href="#">View more</a>
          </figcaption>           
      </figure>
  </div>
  <h2>Sarah</h2>
  <div class="grid">
      <figure class="effect-sarah">
          <img src="https://tympanus.net/Development/HoverEffectIdeas/img/13.jpg" alt="img13"/>
          <figcaption>
              <h2>Free <span>Sarah</span></h2>
              <p>Sarah likes to watch clouds. She's quite depressed.</p>
              <a href="#">View more</a>
          </figcaption>           
      </figure>
      <figure class="effect-sarah">
          <img src="https://tympanus.net/Development/HoverEffectIdeas/img/20.jpg" alt="img20"/>
          <figcaption>
              <h2>Free <span>Sarah</span></h2>
              <p>Sarah likes to watch clouds. She's quite depressed.</p>
              <a href="#">View more</a>
          </figcaption>           
      </figure>
  </div>
  <h2>Chico</h2>
  <div class="grid">
      <figure class="effect-chico">
          <img src="https://tympanus.net/Development/HoverEffectIdeas/img/15.jpg" alt="img15"/>
          <figcaption>
              <h2>Silly <span>Chico</span></h2>
              <p>Chico's main fear was missing the morning bus.</p>
              <a href="#">View more</a>
          </figcaption>           
      </figure>
      <figure class="effect-chico">
          <img src="https://tympanus.net/Development/HoverEffectIdeas/img/4.jpg" alt="img04"/>
          <figcaption>
              <h2>Silly <span>Chico</span></h2>
              <p>Chico's main fear was missing the morning bus.</p>
              <a href="#">View more</a>
          </figcaption>           
      </figure>
  </div>
  <h2>Milo</h2>
  <div class="grid">
      <figure class="effect-milo">
          <img src="https://tympanus.net/Development/HoverEffectIdeas/img/11.jpg" alt="img11"/>
          <figcaption>
              <h2>Faithful <span>Milo</span></h2>
              <p>Milo went to the woods. He took a fun ride and never came back.</p>
              <a href="#">View more</a>
          </figcaption>           
      </figure>
      <figure class="effect-milo">
          <img src="https://tympanus.net/Development/HoverEffectIdeas/img/3.jpg" alt="img03"/>
          <figcaption>
              <h2>Faithful <span>Milo</span></h2>
              <p>Milo went to the woods. He took a fun ride and never came back.</p>
              <a href="#">View more</a>
          </figcaption>           
      </figure>
  </div>
</div>

app/views/stores/new.html.erb
<h1>New Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @store.name %>
</p>

<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>