config/routes.rb
Rails.application.routes.draw do
  resources :stores
  resources :contacts
  resources :resources
  resources :gives
  resources :abouts
  resources :voices
  get 'welcome/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/voice.rb
class Voice < ApplicationRecord
end

app/controllers/voices_controller.rb
class VoicesController < ApplicationController
  before_action :set_voice, only: [:show, :edit, :update, :destroy]

  # GET /voices
  # GET /voices.json
  def index
    @voices = Voice.all
  end

  # GET /voices/1
  # GET /voices/1.json
  def show
  end

  # GET /voices/new
  def new
    @voice = Voice.new
  end

  # GET /voices/1/edit
  def edit
  end

  # POST /voices
  # POST /voices.json
  def create
    @voice = Voice.new(voice_params)

    respond_to do |format|
      if @voice.save
        format.html { redirect_to @voice, notice: 'Voice was successfully created.' }
        format.json { render :show, status: :created, location: @voice }
      else
        format.html { render :new }
        format.json { render json: @voice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /voices/1
  # PATCH/PUT /voices/1.json
  def update
    respond_to do |format|
      if @voice.update(voice_params)
        format.html { redirect_to @voice, notice: 'Voice was successfully updated.' }
        format.json { render :show, status: :ok, location: @voice }
      else
        format.html { render :edit }
        format.json { render json: @voice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /voices/1
  # DELETE /voices/1.json
  def destroy
    @voice.destroy
    respond_to do |format|
      format.html { redirect_to voices_url, notice: 'Voice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_voice
      @voice = Voice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def voice_params
      params.require(:voice).permit(:name)
    end
end

app/helpers/voices_helper.rb
module VoicesHelper
end

app/views/voices/_form.html.erb
<%= form_with(model: voice, local: true) do |form| %>
  <% if voice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(voice.errors.count, "error") %> prohibited this voice from being saved:</h2>

      <ul>
        <% voice.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/voices/edit.html.erb
<h1>Editing Voice</h1>

<%= render 'form', voice: @voice %>

<%= link_to 'Show', @voice %> |
<%= link_to 'Back', voices_path %>

app/views/voices/index.html.erb
<!-- Header -->
<header class="masthead" style="height: 100px;">
  <div class="container d-flex h-100 align-items-center">
    <div class="mx-auto text-center">
      <br><br><br><br>
      <h1 class="animated fadeInDownBig" style="font-size: 3em;">VOICE MINISTRY</h1>
      <p>
      <h1 style="font-size: 1.5em;">BELIEVE SPEAK ACT</h1>
    </div>
  </div>
</header>

<!-- Voicing Section -->
<section id="Voicing" class="projects-section bg-light">
  <div class="container">
    <div class="row align-items-center no-gutters mb-4 mb-lg-5">
      <div class="col-xl-6 col-lg-7">
        <%= image_tag("2_Corinthians_4_13.jpg", {:class => "img-fluid mb-3 mb-lg-0", :style => "height:400px;width:500px;"}) %>
      </div>
      <div class="col-xl-6 col-lg-5">
        <div class="featured-text text-center text-lg-left">
          <h1 style="color: #62c6bb; font-size: 5em;">VOICING</h1>
          <p>
          <h2 class="text-black-100 mx-auto mt-2 mb-5 text-left">
            Voicing means to speak, command or decree whatever circumstances or situations to align to the Will of God! <p>
            Where there is true faith, and the true Spirit of faith, there will be a speaking of, for, and in the name of Christ, as there ought to be: for "whosoever shall say unto this mountain, be thou removed, and be thou cast into the sea; and shall not doubt in his heart, but shall believe that those things which he saith shall come to pass; he shall have whatsoever he saith."
          </h2>
          <a href="https://www.youtube.com/playlist?list=PLwuMb6Dl2ytPWct7WlHzW47aPaM4dCS_r" target="_blank">
            <button type="button" class="btn btn-primary">LEARN MORE</button>
          </a>
        </div>
      </div>
    </div>
</section>

<!-- Overcoming Section -->
<section id="Overcoming" class="projects-section bg-light">
  <div class="container">
    <div class="row align-items-center no-gutters mb-4 mb-lg-5">
      <div class="col-xl-6 col-lg-7">
        <%= image_tag("1_John_5_4.jpg", {:class => "img-fluid mb-3 mb-lg-0", :style => "height:400px;width:500px;"}) %>
      </div>
      <div class="col-xl-6 col-lg-5">
        <div class="featured-text text-center text-lg-left">
          <h1 style="color: #62c6bb; font-size: 5em;">OVERCOMING</h1>
          <p>
          <h2 class="text-black-100 mx-auto mt-2 mb-5 text-left">
            Overcoming means to exert dominion and manifest as sons of God on this earth! <p>
            Which may be understood either of persons born; of God; or of the new creature, or principle of grace wrought in them, particularly faith hereafter mentioned, which is an heaven born grace, the gift of God, and the operation of his Spirit.
          </h2>
          <a href="https://www.youtube.com/playlist?list=PLwuMb6Dl2ytPpveLuoU6zOcLCU6NzbOdf" target="_blank">
            <button type="button" class="btn btn-primary">LEARN MORE</button>
          </a>
        </div>
      </div>
    </div>
</section>

<!-- Indwelling Section -->
<section id="Indwelling" class="projects-section bg-light">
  <div class="container">
    <div class="row align-items-center no-gutters mb-4 mb-lg-5">
      <div class="col-xl-6 col-lg-7">
        <%= image_tag("John_14_17.jpg", {:class => "img-fluid mb-3 mb-lg-0", :style => "height:400px;width:500px;"}) %>
      </div>
      <div class="col-xl-6 col-lg-5">
        <div class="featured-text text-center text-lg-left">
          <h1 style="color: #62c6bb; font-size: 5em;">INDWELLING</h1>
          <p>
          <h2 class="text-black-100 mx-auto mt-2 mb-5 text-left">
            Indwelling means to abide in the Holy Spirit who is greater than he who is in the world!<p>
            The indwelling of the Holy Spirit, through whom the Father and the Son also dwell, guarantees our positions as sons and heirs of God through Christ: for "because ye are sons, God hath sent forth the Spirit of his Son into your hearts, crying, Abba, Father."
          </h2>
          <a href="https://www.youtube.com/playlist?list=PLwuMb6Dl2ytPJS88mvM_rnnFQDQHxntte" target="_blank">
            <button type="button" class="btn btn-primary">LEARN MORE</button>
          </a>
        </div>
      </div>
    </div>
</section>

<!-- Conquering Section -->
<section id="Conquering" class="projects-section bg-light">
  <div class="container">
    <div class="row align-items-center no-gutters mb-4 mb-lg-5">
      <div class="col-xl-6 col-lg-7">
        <%= image_tag("Romans_8_37.jpg", {:class => "img-fluid mb-3 mb-lg-0", :style => "height:400px;width:500px;"}) %>
      </div>
      <div class="col-xl-6 col-lg-5">
        <div class="featured-text text-center text-lg-left">
          <h1 style="color: #62c6bb; font-size: 5em;">CONQUERING</h1>
          <p>
          <h2 class="text-black-100 mx-auto mt-2 mb-5 text-left">
            Conquering means to triumph in Christ always!<p>
            Not only over sin and Satan, but the world which we cheerfully and courageously undergo, insomuch that we are not only conquerors, but "more than conquerors": we have above overcome, we have exceedingly the better of it; our experience, faith, and joy, are often increased by them; we have got the victory with ease, over Satan "by the blood of the Lamb, and the word of their testimony."
          </h2>
          <a href="https://www.youtube.com/playlist?list=PLwuMb6Dl2ytOb8NkWL4dq_Q2oDgi_XLJi" target="_blank">
            <button type="button" class="btn btn-primary">LEARN MORE</button>
          </a>
        </div>
      </div>
    </div>
</section>

<!-- Empowering Section -->
<section id="Empowering" class="projects-section bg-light">
  <div class="container">
    <div class="row align-items-center no-gutters mb-4 mb-lg-5">
      <div class="col-xl-6 col-lg-7">
        <%= image_tag("Luke_10_19.jpg", {:class => "img-fluid mb-3 mb-lg-0", :style => "height:400px;width:500px;"}) %>
      </div>
      <div class="col-xl-6 col-lg-5">
        <div class="featured-text text-center text-lg-left">
          <h1 style="color: #62c6bb; font-size: 5em;">EMPOWERING</h1>
          <p>
          <h2 class="text-black-100 mx-auto mt-2 mb-5 text-left">
            Empowering means to walk in the fullness of the power of God!<p>
            The abiding of the Spirit of living God throught whom "Christ liveth in me: and the life which I now live in the flesh I live by the faith of the Son of God" through which we have the full access to the power of God and mind of Christ.
          </h2>
          <a href="https://www.youtube.com/playlist?list=PLwuMb6Dl2ytNV1g6Tij3Jk0qhxcg7jjxJ" target="_blank">
            <button type="button" class="btn btn-primary">LEARN MORE</button>
          </a>
        </div>
      </div>
    </div>
</section>

app/views/voices/new.html.erb
<h1>New Voice</h1>

<%= render 'form', voice: @voice %>

<%= link_to 'Back', voices_path %>

app/views/voices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @voice.name %>
</p>

<%= link_to 'Edit', edit_voice_path(@voice) %> |
<%= link_to 'Back', voices_path %>