config/routes.rb
Rails.application.routes.draw do
  resources :stores
  resources :contacts
  resources :resources
  resources :gives
  resources :abouts
  resources :voices
  get 'welcome/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/about.rb
class About < ApplicationRecord
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  before_action :set_about, only: [:show, :edit, :update, :destroy]

  # GET /abouts
  # GET /abouts.json
  def index
    @abouts = About.all
  end

  # GET /abouts/1
  # GET /abouts/1.json
  def show
  end

  # GET /abouts/new
  def new
    @about = About.new
  end

  # GET /abouts/1/edit
  def edit
  end

  # POST /abouts
  # POST /abouts.json
  def create
    @about = About.new(about_params)

    respond_to do |format|
      if @about.save
        format.html { redirect_to @about, notice: 'About was successfully created.' }
        format.json { render :show, status: :created, location: @about }
      else
        format.html { render :new }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /abouts/1
  # PATCH/PUT /abouts/1.json
  def update
    respond_to do |format|
      if @about.update(about_params)
        format.html { redirect_to @about, notice: 'About was successfully updated.' }
        format.json { render :show, status: :ok, location: @about }
      else
        format.html { render :edit }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /abouts/1
  # DELETE /abouts/1.json
  def destroy
    @about.destroy
    respond_to do |format|
      format.html { redirect_to abouts_url, notice: 'About was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_about
      @about = About.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def about_params
      params.require(:about).permit(:name)
    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/views/abouts/_form.html.erb
<%= form_with(model: about, local: true) do |form| %>
  <% if about.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(about.errors.count, "error") %> prohibited this about from being saved:</h2>

      <ul>
        <% about.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/abouts/edit.html.erb
<h1>Editing About</h1>

<%= render 'form', about: @about %>

<%= link_to 'Show', @about %> |
<%= link_to 'Back', abouts_path %>

app/views/abouts/index.html.erb
<!-- Header -->
<header class="masthead" style="height: 100px;">
  <div class="container d-flex h-100 align-items-center">
    <div class="mx-auto text-center">
      <br><br><br><br>
      <h1 class="animated fadeInDownBig" style="font-size: 3em;">ABOUT</h1>
      <p>
      <h1 style="font-size: 1.5em;">WE DO THE WORD AND GOD DOES THE WORK</h1>
    </div>
  </div>
</header>


<!-- About Section -->
<section id="about" class="projects-section bg-light">
  <div class="container">
  <div class="grid">
      <figure class="effect-layla">
          <%= image_tag("VoiceOfHeavenLogo.JPG", {:class => "img-fluid mb-3 mb-lg-0", :style => "height:388px;width:500px;"}) %>
          <figcaption>
              <h2>Voice <span>of <span>Heaven</span></h2>
              <h3>When Voice of Heaven comes, it brings the divine perspective!</h3>
              <a href="#">View more</a>
          </figcaption>           
      </figure>
      <figure class="effect-layla">
        <div class="featured-text text-center text-lg-left">
          <h1 style="color: #62c6bb; font-size: 5em;">VOICE OF HEAVEN</h1>
          <h3 class="text-black-100 mx-auto mt-2 mb-5 text-left">
            Voice of Heaven starts with a revelation and a dream. The revelation is about our True Identity in Christ: we are sons and heirs of God through Christ and the faith of Him, which bestowed to us by His grace when we were born again, empowers us to walk in the fullness of the power of God and the mind of Christ to manifest as sons of God to exert dominion, destroy the works of Devil and as Jesus said: "he that believeth on me, the works that I do shall he do also; and greater works than these shall he do; because I go unto my Father."
          </h3> 
        </div>        
      </figure>
  </div>
    </div>
</section>

app/views/abouts/new.html.erb
<h1>New About</h1>

<%= render 'form', about: @about %>

<%= link_to 'Back', abouts_path %>

app/views/abouts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @about.name %>
</p>

<%= link_to 'Edit', edit_about_path(@about) %> |
<%= link_to 'Back', abouts_path %>