config/routes.rb
Rails.application.routes.draw do
  resources :stores
  resources :contacts
  resources :resources
  resources :gives
  resources :abouts
  resources :voices
  get 'welcome/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/about.rb
class About < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/give.rb
class Give < ApplicationRecord
end

app/models/resource.rb
class Resource < ApplicationRecord
end

app/models/store.rb
class Store < ApplicationRecord
end

app/models/voice.rb
class Voice < ApplicationRecord
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  before_action :set_about, only: [:show, :edit, :update, :destroy]

  # GET /abouts
  # GET /abouts.json
  def index
    @abouts = About.all
  end

  # GET /abouts/1
  # GET /abouts/1.json
  def show
  end

  # GET /abouts/new
  def new
    @about = About.new
  end

  # GET /abouts/1/edit
  def edit
  end

  # POST /abouts
  # POST /abouts.json
  def create
    @about = About.new(about_params)

    respond_to do |format|
      if @about.save
        format.html { redirect_to @about, notice: 'About was successfully created.' }
        format.json { render :show, status: :created, location: @about }
      else
        format.html { render :new }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /abouts/1
  # PATCH/PUT /abouts/1.json
  def update
    respond_to do |format|
      if @about.update(about_params)
        format.html { redirect_to @about, notice: 'About was successfully updated.' }
        format.json { render :show, status: :ok, location: @about }
      else
        format.html { render :edit }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /abouts/1
  # DELETE /abouts/1.json
  def destroy
    @about.destroy
    respond_to do |format|
      format.html { redirect_to abouts_url, notice: 'About was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_about
      @about = About.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def about_params
      params.require(:about).permit(:name)
    end
end

app/controllers/gives_controller.rb
class GivesController < ApplicationController
  before_action :set_gife, only: [:show, :edit, :update, :destroy]

  # GET /gives
  # GET /gives.json
  def index
    @gives = Give.all
  end

  # GET /gives/1
  # GET /gives/1.json
  def show
  end

  # GET /gives/new
  def new
    @gife = Give.new
  end

  # GET /gives/1/edit
  def edit
  end

  # POST /gives
  # POST /gives.json
  def create
    @gife = Give.new(gife_params)

    respond_to do |format|
      if @gife.save
        format.html { redirect_to @gife, notice: 'Give was successfully created.' }
        format.json { render :show, status: :created, location: @gife }
      else
        format.html { render :new }
        format.json { render json: @gife.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gives/1
  # PATCH/PUT /gives/1.json
  def update
    respond_to do |format|
      if @gife.update(gife_params)
        format.html { redirect_to @gife, notice: 'Give was successfully updated.' }
        format.json { render :show, status: :ok, location: @gife }
      else
        format.html { render :edit }
        format.json { render json: @gife.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gives/1
  # DELETE /gives/1.json
  def destroy
    @gife.destroy
    respond_to do |format|
      format.html { redirect_to gives_url, notice: 'Give was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gife
      @gife = Give.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gife_params
      params.require(:gife).permit(:name)
    end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:name)
    end
end

app/controllers/voices_controller.rb
class VoicesController < ApplicationController
  before_action :set_voice, only: [:show, :edit, :update, :destroy]

  # GET /voices
  # GET /voices.json
  def index
    @voices = Voice.all
  end

  # GET /voices/1
  # GET /voices/1.json
  def show
  end

  # GET /voices/new
  def new
    @voice = Voice.new
  end

  # GET /voices/1/edit
  def edit
  end

  # POST /voices
  # POST /voices.json
  def create
    @voice = Voice.new(voice_params)

    respond_to do |format|
      if @voice.save
        format.html { redirect_to @voice, notice: 'Voice was successfully created.' }
        format.json { render :show, status: :created, location: @voice }
      else
        format.html { render :new }
        format.json { render json: @voice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /voices/1
  # PATCH/PUT /voices/1.json
  def update
    respond_to do |format|
      if @voice.update(voice_params)
        format.html { redirect_to @voice, notice: 'Voice was successfully updated.' }
        format.json { render :show, status: :ok, location: @voice }
      else
        format.html { render :edit }
        format.json { render json: @voice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /voices/1
  # DELETE /voices/1.json
  def destroy
    @voice.destroy
    respond_to do |format|
      format.html { redirect_to voices_url, notice: 'Voice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_voice
      @voice = Voice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def voice_params
      params.require(:voice).permit(:name)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

def active_class?(class_name = nil, path)
  class_name ||= ""
  class_name += " active" if current_page?(path)
  class_name.strip!
  return class_name
end

end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/gives_helper.rb
module GivesHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/voices_helper.rb
module VoicesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns:og="http://opengraphprotocol.org/schema/" xmlns:fb="http://www.facebook.com/2008/fbml" lang="en-US"  >
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta charset="utf-8">
    <title>Voice of Heaven</title>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1" name="viewport">

    <meta property="og:site_name" content="Voice of Heaven Ministries"/>
    <meta property="og:title" content="VOICEofHeaven &mdash; VOH Ministries"/>
    <meta property="og:url" content="http://www.voiceoftheheaven.com"/>
    <meta property="og:type" content="website"/>
    <meta itemprop="name" content="VOICEofHeaven — VOH Ministries"/>
    <meta itemprop="url" content="https://www.voiceoftheheaven.com"/>
    <meta name="twitter:title" content="VOICEofHeaven — VOH Ministries"/>
    <meta name="twitter:url" content="https://www.twitter.com/MyVoiceOfHeaven"/>
    <meta name="twitter:card" content="summary"/>
    <meta name="description" content="" />

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6/html5shiv.min.js"></script>
    <![endif]-->

    <!-- Google Adsense Script -->
    <script data-ad-client="ca-pub-8765787848226338" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

    <!-- Animation -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">

    <!-- Cool CSS Effects -->
    <link href='https://fonts.googleapis.com/css?family=Raleway:400,800,300' rel='stylesheet' type='text/css'>

    <!-- Load an icon library to show a hamburger menu (bars) on small screens -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Bootstrap core CSS -->
    <link href="https://blackrockdigital.github.io/startbootstrap-grayscale/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="https://blackrockdigital.github.io/startbootstrap-grayscale/vendor/fontawesome-free/css/all.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="https://blackrockdigital.github.io/startbootstrap-grayscale/css/grayscale.min.css" rel="stylesheet">

    <!-- Navigation -->
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="<%= root_path %>">
        <%= image_tag("VoiceOfHeavenLogo.png", {:class => "d-inline-block align-top", :style => "height:30px;width:30px;"}) %>
        <strong>VOICE OF HEAVEN</strong>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="https://www.youtube.com/channel/UCOv7i1ojVrfHxMj2KAuKxtg" target="_blank">
        <strong>SUBSCRIBE ON YOUTUBE</strong>
      </a>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item dropdown <%= active_class?(voices_path) %>">
            <%= link_to "#", id: "navbarDropdownMenuLink", class: "navbar-brand nav-link dropdown-toggle", data: { toggle: "dropdown" }, aria: { haspopup: true, expanded: false } do %>
              VOICE
            <% end %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="<%= voices_path %>"><strong>VOICING</strong></a>
              <a class="dropdown-item" href="<%= voices_path %>#Overcoming"><strong>OVERCOMING</strong></a>
              <a class="dropdown-item" href="<%= voices_path %>#Indwelling"><strong>INDWELLING</strong></a>
              <a class="dropdown-item" href="<%= voices_path %>#Conquering"><strong>CONQUERING</strong></a>
              <a class="dropdown-item" href="<%= voices_path %>#Empowering"><strong>EMPOWERING</strong></a>
            </div>
          </li>
          <li class="nav-item <%= active_class?(resources_path) %>">
            <a class="navbar-brand nav-link" href="<%= resources_path %>">WATCH</a>
          </li>
          <li class="nav-item <%= active_class?(abouts_path) %>">
            <a class="navbar-brand nav-link" href="<%= abouts_path %>">ABOUT</a>
          </li>
          <!--
          <li class="nav-item <%= active_class?(stores_path) %>">
            <a class="navbar-brand nav-link" href="<%= stores_path %>">STORE</a>
          </li>
          -->
          <li class="nav-item <%= active_class?(gives_path) %>">
            <a class="navbar-brand nav-link" href="<%= gives_path %>">GIVE</a>
          </li>
          <li class="nav-item <%= active_class?(contacts_path) %>">
            <a class="navbar-brand nav-link" href="<%= contacts_path %>">CONTACT</a>
          </li>
        </ul>
      </div>
    </nav>

  </head>

  <body>
    <%= yield %>
  </body>

  <!-- Footer -->
    <footer class="bg-black small text-center text-white-50">
      <div class="container">
        Copyright &copy; Voice of Heaven 2020
      </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="https://blackrockdigital.github.io/startbootstrap-grayscale/vendor/jquery/jquery.min.js"></script>
    <script src="https://blackrockdigital.github.io/startbootstrap-grayscale/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="https://blackrockdigital.github.io/startbootstrap-grayscale/vendor/jquery-easing/jquery.easing.min.js"></script>

</html>

app/views/resources/_form.html.erb
<%= form_with(model: resource, local: true) do |form| %>
  <% if resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
        <% resource.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/resources/edit.html.erb
<h1>Editing Resource</h1>

<%= render 'form', resource: @resource %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<!-- Header -->
<header class="masthead" style="height: 100px;">
  <div class="container d-flex h-100 align-items-center">
    <div class="mx-auto text-center">
      <br><br><br><br>
      <h1 class="animated fadeInDownBig" style="font-size: 3em;">WATCH ONLINE</h1>
      <p>
      <h1 style="font-size: 1.5em;">WE DO THE WORD AND GOD DOES THE WORK</h1>
    </div>
  </div>
</header>

<!-- Recent Message Section -->
<section id="RecentMessage" class="projects-section bg-light">
  <div class="container">
    <div class="row align-items-center no-gutters mb-4 mb-lg-5">
      <div class="col-xl-6 col-lg-7">
        <iframe width="325" height="315" src="https://www.youtube.com/embed/vLBnEx-hc4M" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div>
      <div class="col-xl-6 col-lg-5">
        <div class="featured-text text-center text-lg-left">
          <h1 style="color: #62c6bb; font-size: 5em;">RECENT MESSAGE</h1>
          <p>
          <h2 class="text-black-100 mx-auto mt-2 mb-5 text-left">
            Rediscover your favorite messages in the archive. You can watch or listen to messages on your own schedule and easily share with friends!
          </h2>
          <a href="https://www.youtube.com/playlist?list=PLwuMb6Dl2ytOsAPhJmCYOkGIOzbHQi3Iq" target="_blank">
            <button type="button" class="btn btn-primary">WATCH NOW</button>
          </a>
        </div>
      </div>
    </div>
</section>

<!-- Watch Live Section -->
<section id="WatchLive" class="projects-section bg-light">
  <div class="container">
    <div class="row align-items-center no-gutters mb-4 mb-lg-5">
      <div class="col-xl-6 col-lg-7">
        <iframe width="325" height="315" src="https://www.youtube.com/embed/vLBnEx-hc4M" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div>
      <div class="col-xl-6 col-lg-5">
        <div class="featured-text text-center text-lg-left">
          <h1 style="color: #62c6bb; font-size: 5em;">WATCH LIVE</h1>
          <p>
          <h2 class="text-black-100 mx-auto mt-2 mb-5 text-left">
            You can now be a part of Voice of Heaven ministry through the streaming live no matter where you are!<p>
            Be sure to subscribe!
          </h2>
          <a href="https://www.youtube.com/playlist?list=PLwuMb6Dl2ytMh9PP7zWARy0NfFQwq5LOb" target="_blank">
            <button type="button" class="btn btn-primary">WATCH NOW</button>
          </a>
        </div>
      </div>
    </div>
</section>

app/views/resources/new.html.erb
<h1>New Resource</h1>

<%= render 'form', resource: @resource %>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @resource.name %>
</p>

<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>